// <auto-generated />
using System;
using IntranetPortal.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntranetPortal.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424160358_AddAttendanceLogs")]
    partial class AddAttendanceLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IntranetPortal.Data.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SiteId");

                    b.ToTable("Core_Announcements", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.Accessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("MinStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SiteId");

                    b.ToTable("AM_Accessories", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AccessoryCheckout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FulfilledByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RequestedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("FulfilledByEmployeeId");

                    b.HasIndex("RequestedByEmployeeId");

                    b.ToTable("AM_AccessoryCheckouts", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.ApproverGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AM_ApproverGroups", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.ApproverGroupMember", b =>
                {
                    b.Property<int>("ApproverGroupId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("ApproverGroupId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AM_ApproverGroupMembers", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.ApproverGroupScope", b =>
                {
                    b.Property<int>("ApproverGroupId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("ApproverGroupId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("AM_ApproverGroupScopes", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("PhysicalLocation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("WarrantyExpiration")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ModelId");

                    b.HasIndex("SiteId");

                    b.ToTable("AM_Assets", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("AssignedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToTeamId")
                        .HasColumnType("int");

                    b.Property<string>("ConditionOnAssign")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ConditionOnReturn")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpectedReturnDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReturnedByEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssignedByEmployeeId");

                    b.HasIndex("AssignedToEmployeeId");

                    b.HasIndex("AssignedToTeamId");

                    b.HasIndex("ReturnedByEmployeeId");

                    b.ToTable("AM_AssetAssignments", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext");

                    b.Property<int>("PerformedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PerformedByEmployeeId");

                    b.ToTable("AM_AssetAuditLogs", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowRequesterToSelectApprover")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DefaultApproverGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("FulfillmentGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultApproverGroupId");

                    b.HasIndex("FulfillmentGroupId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("AM_AssetCategories", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetCategoryApproverGroup", b =>
                {
                    b.Property<int>("AssetCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ApproverGroupId")
                        .HasColumnType("int");

                    b.HasKey("AssetCategoryId", "ApproverGroupId");

                    b.HasIndex("ApproverGroupId");

                    b.ToTable("AM_AssetCategoryApproverGroups", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("LoggedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RepairVendor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("LoggedByEmployeeId");

                    b.ToTable("AM_AssetMaintenance", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("AM_AssetModels", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RequestedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedForEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByEmployeeId");

                    b.HasIndex("RequestedForEmployeeId");

                    b.ToTable("AM_AssetRequests", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetRequestLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ApprovedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("AssetRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedApproverGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedAssetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FulfilledByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedAccessoryId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedModelId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByEmployeeId");

                    b.HasIndex("AssetRequestId");

                    b.HasIndex("AssignedApproverGroupId");

                    b.HasIndex("AssignedAssetId");

                    b.HasIndex("FulfilledByEmployeeId");

                    b.HasIndex("RequestedAccessoryId");

                    b.HasIndex("RequestedCategoryId");

                    b.HasIndex("RequestedModelId");

                    b.HasIndex("SelectedApproverEmployeeId");

                    b.ToTable("AM_AssetRequestLineItems", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Core_AuditLogs", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Core_Departments", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("SiteId");

                    b.HasIndex("TeamId");

                    b.ToTable("Core_Employees", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClockInTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeRecordId", "Date")
                        .IsUnique();

                    b.ToTable("HR_AttendanceLogs", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("HR_Departments", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.EmployeeOnboardingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssigneeRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("EmployeeRecordId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeRecordId");

                    b.ToTable("HR_EmployeeOnboardingTasks", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.EmployeeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("DirectManagerId")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DirectManagerId");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("HR_EmployeeRecords", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("EmployeeRecordId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("HR_LeaveRequests", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysAllowed")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("HR_LeaveTypes", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.OnboardingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssigneeRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("HR_OnboardingTasks", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.OnboardingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("HR_OnboardingTemplates", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.LoginChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChallengeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("NormalizedEmail", "CreatedAt");

                    b.ToTable("Core_LoginChallenges", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Core_Permissions", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("HR_Positions", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Core_Roles", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.RoleDelegation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SourceUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SubstituteUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceUserId");

                    b.HasIndex("SubstituteUserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Core_RoleDelegations", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Core_RolePermissions", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Core_Sites", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.SystemModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IconSvg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActiveGlobally")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Core_SystemModules", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Core_Teams", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SecurityStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.ToTable("Core_UserAccounts", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SiteId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Core_UserRoles", (string)null);
                });

            modelBuilder.Entity("SiteSystemModule", b =>
                {
                    b.Property<int>("AllowedModulesId")
                        .HasColumnType("int");

                    b.Property<int>("AllowedSitesId")
                        .HasColumnType("int");

                    b.HasKey("AllowedModulesId", "AllowedSitesId");

                    b.HasIndex("AllowedSitesId");

                    b.ToTable("Core_ModuleSites", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Announcement", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Employee", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.Navigation("Author");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.Accessory", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Assets.AssetCategory", "Category")
                        .WithMany("Accessories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Department");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AccessoryCheckout", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Assets.Accessory", "Accessory")
                        .WithMany("Checkouts")
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Employee", "FulfilledByEmployee")
                        .WithMany()
                        .HasForeignKey("FulfilledByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Employee", "RequestedByEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("FulfilledByEmployee");

                    b.Navigation("RequestedByEmployee");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.ApproverGroupMember", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Assets.ApproverGroup", "ApproverGroup")
                        .WithMany("Members")
                        .HasForeignKey("ApproverGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverGroup");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.ApproverGroupScope", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Assets.ApproverGroup", "ApproverGroup")
                        .WithMany("Scopes")
                        .HasForeignKey("ApproverGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverGroup");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.Asset", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntranetPortal.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Assets.AssetModel", "Model")
                        .WithMany("Assets")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Department");

                    b.Navigation("Model");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetAssignment", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Assets.Asset", "Asset")
                        .WithMany("Assignments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Employee", "AssignedByEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Employee", "AssignedToEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Team", "AssignedToTeam")
                        .WithMany()
                        .HasForeignKey("AssignedToTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Employee", "ReturnedByEmployee")
                        .WithMany()
                        .HasForeignKey("ReturnedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("AssignedByEmployee");

                    b.Navigation("AssignedToEmployee");

                    b.Navigation("AssignedToTeam");

                    b.Navigation("ReturnedByEmployee");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetAuditLog", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Assets.Asset", "Asset")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Employee", "PerformedByEmployee")
                        .WithMany()
                        .HasForeignKey("PerformedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("PerformedByEmployee");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetCategory", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Assets.ApproverGroup", "DefaultApproverGroup")
                        .WithMany()
                        .HasForeignKey("DefaultApproverGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntranetPortal.Data.Models.Assets.ApproverGroup", "FulfillmentGroup")
                        .WithMany()
                        .HasForeignKey("FulfillmentGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntranetPortal.Data.Models.Assets.AssetCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultApproverGroup");

                    b.Navigation("FulfillmentGroup");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetCategoryApproverGroup", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Assets.ApproverGroup", "ApproverGroup")
                        .WithMany("AssetCategories")
                        .HasForeignKey("ApproverGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Assets.AssetCategory", "AssetCategory")
                        .WithMany("ApproverGroups")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApproverGroup");

                    b.Navigation("AssetCategory");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetMaintenance", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Assets.Asset", "Asset")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Employee", "LoggedByEmployee")
                        .WithMany()
                        .HasForeignKey("LoggedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("LoggedByEmployee");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetModel", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Assets.AssetCategory", "Category")
                        .WithMany("Models")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetRequest", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Employee", "RequestedByEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Employee", "RequestedForEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedForEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestedByEmployee");

                    b.Navigation("RequestedForEmployee");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetRequestLineItem", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Employee", "ApprovedByEmployee")
                        .WithMany()
                        .HasForeignKey("ApprovedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Assets.AssetRequest", "AssetRequest")
                        .WithMany("LineItems")
                        .HasForeignKey("AssetRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Assets.ApproverGroup", "AssignedApproverGroup")
                        .WithMany()
                        .HasForeignKey("AssignedApproverGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Assets.Asset", "AssignedAsset")
                        .WithMany()
                        .HasForeignKey("AssignedAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Employee", "FulfilledByEmployee")
                        .WithMany()
                        .HasForeignKey("FulfilledByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Assets.Accessory", "RequestedAccessory")
                        .WithMany()
                        .HasForeignKey("RequestedAccessoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Assets.AssetCategory", "RequestedCategory")
                        .WithMany()
                        .HasForeignKey("RequestedCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Assets.AssetModel", "RequestedModel")
                        .WithMany()
                        .HasForeignKey("RequestedModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Employee", "SelectedApproverEmployee")
                        .WithMany()
                        .HasForeignKey("SelectedApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByEmployee");

                    b.Navigation("AssetRequest");

                    b.Navigation("AssignedApproverGroup");

                    b.Navigation("AssignedAsset");

                    b.Navigation("FulfilledByEmployee");

                    b.Navigation("RequestedAccessory");

                    b.Navigation("RequestedCategory");

                    b.Navigation("RequestedModel");

                    b.Navigation("SelectedApproverEmployee");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Department", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Employee", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId");

                    b.HasOne("IntranetPortal.Data.Models.Site", "Site")
                        .WithMany("Employees")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Team", "Team")
                        .WithMany("Employees")
                        .HasForeignKey("TeamId");

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("Site");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.AttendanceLog", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.HR.EmployeeRecord", "EmployeeRecord")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("EmployeeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeRecord");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.Department", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.HR.EmployeeRecord", "Manager")
                        .WithMany("ManagedDepartments")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntranetPortal.Data.Models.HR.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.EmployeeOnboardingTask", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.HR.EmployeeRecord", "EmployeeRecord")
                        .WithMany("OnboardingTasks")
                        .HasForeignKey("EmployeeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeRecord");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.EmployeeRecord", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.HR.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntranetPortal.Data.Models.HR.EmployeeRecord", "DirectManager")
                        .WithMany("DirectReports")
                        .HasForeignKey("DirectManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntranetPortal.Data.Models.UserAccount", "UserAccount")
                        .WithOne()
                        .HasForeignKey("IntranetPortal.Data.Models.HR.EmployeeRecord", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("DirectManager");

                    b.Navigation("Position");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.LeaveRequest", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.HR.EmployeeRecord", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntranetPortal.Data.Models.HR.EmployeeRecord", "EmployeeRecord")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.HR.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("EmployeeRecord");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.OnboardingTask", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.HR.OnboardingTemplate", "Template")
                        .WithMany("Tasks")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.LoginChallenge", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.RoleDelegation", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.UserAccount", "SourceUser")
                        .WithMany()
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.UserAccount", "SubstituteUser")
                        .WithMany()
                        .HasForeignKey("SubstituteUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceUser");

                    b.Navigation("SubstituteUser");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.RolePermission", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Team", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.UserAccount", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.UserRole", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("IntranetPortal.Data.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.HasOne("IntranetPortal.Data.Models.UserAccount", "UserAccount")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");

                    b.Navigation("Site");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SiteSystemModule", b =>
                {
                    b.HasOne("IntranetPortal.Data.Models.SystemModule", null)
                        .WithMany()
                        .HasForeignKey("AllowedModulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Data.Models.Site", null)
                        .WithMany()
                        .HasForeignKey("AllowedSitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.Accessory", b =>
                {
                    b.Navigation("Checkouts");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.ApproverGroup", b =>
                {
                    b.Navigation("AssetCategories");

                    b.Navigation("Members");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.Asset", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("AuditLogs");

                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetCategory", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("ApproverGroups");

                    b.Navigation("Models");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetModel", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Assets.AssetRequest", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.EmployeeRecord", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("DirectReports");

                    b.Navigation("LeaveRequests");

                    b.Navigation("ManagedDepartments");

                    b.Navigation("OnboardingTasks");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.HR.OnboardingTemplate", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Site", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.Team", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IntranetPortal.Data.Models.UserAccount", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
